### ISSUE TITLE
db 설계 정리

### ISSUE THREAD

**Issue by jongin1004** [KimJinsu66/WebTeamProject#5]
[Db 설계 정리.txt](https://github.com/KimJinsu66/WebTeamProject/files/5025893/Db.txt)

게시판  

국가: 네비게이션 바를 띄울 뿐 링크는 각 국가로 건다. 
	->각 국가로 이동을 하게되면 각 국가별 미디어 메인 페이지로 이동.

미디어: 영화,드라마,애니메이션,다큐 (같은페이지에 있고 각 네비게이션 바를누를시 이동) 
	프론트: 6페이지(한국) 크게는 3페이지(나머지는 복붙&DB내용 조금 만지면됨)
		각 장르별 게시판(4페이지), 메인미디어페이지(1페이지),글쓰기페이지(1페이지)
	백엔드: DB : 회원정보(1개) and 국가별(국가개수만큼)> 장르별(4개)   => DB 2개 테이블 5개

리뷰: 글쓰기페이지(1페이지):수정 > 추천리포트 기능 구현을하여 기준을 정해 리뷰페이지(1페이지)로 넘긴다.

건의사항: 글쓰기페이지(1페이지):수정 > 건의사항 페이지에 넘긴다(1페이지)

8.5(수) : 메인페이지 수정 중(승수), 미디어게시판글쓰기 수정 중(종인), 미디어메인페이지 시작(종화), 로그인페이지 수정 중(진수)

메인 > 로그인페이지, 국가별 메인페이지>글쓰기 
	
	로그인 DB에 회원정보 저장.

8.6(목) :

**Comment by KimJinsu66** [comment]
참잘했어요

**Comment by KimJinsu66** [comment]
very good

**Comment by KimJinsu66** [comment]
dasdasd
